### ISSUE TITLE
Connect mobile and web to Syncspace-Server

### ISSUE THREAD

**Issue by tylerminnis** [Sync-Space-49/syncspace-mobile#54]
Tuesday at Landing

![Image](https://github.com/Sync-Space-49/syncspace-mobile/assets/26585103/b537ae87-b755-4e54-8e61-bc4945429160)

**Comment by DylanHalstead** [comment]
Yeah... Still work to do but at least some paths to try out and see what they do.

Will be working with @kfinberg7581, @tylerminnis,a dn @Nathan-Laney Thursday to try and make more progress
