### ISSUE TITLE
Getting Boards from DB and rendering

### ISSUE THREAD

**Issue by sumiv** [Sync-Space-49/syncspace-mobile#62]

**Comment by tylerminnis** [comment]
this is for rendering on specific board page: 

- update router to display board by boardId
- needs to render stacks and associated cards
- update board title
- update board settings

**Comment by tylerminnis** [comment]
@DylanHalstead if u have time to help out, could you get the requests needed for rendering a specific board (so getDetailedBoard, getBoardMembers, updateBoard, deleteBoard, addBoardMembers on Board.tsx) and mobile will figure out the rendering part

**Comment by DylanHalstead** [comment]
lol getBoardMembers is not functional yet so put a pin in that for now
