### ISSUE TITLE
AI implementation

### ISSUE THREAD

**Issue by tylerminnis** [Sync-Space-49/syncspace-mobile#98]
acceptance criteria: 

when adding new board, you have the option to create board with ai or not
for AI

- on specific board, new board w/ ai should either open a modal or new page with inputs
- inputs are title, description, detail_level (brief, detailed, very detailed), story_point_type (fibonacci, tshirt size, 1-5)
- chatgpt response takes a while so while waiting for axios response, have spinner appear until response is back (15 seconds)
- when response is done, close modal and route to new board

**Comment by tylerminnis** [comment]
blocked until server gets gpt requests done

**Comment by DylanHalstead** [comment]
We done
